
-- Drop duplicate triggers that were causing likes_count / comments_count /
-- notifications / follower counts to double up on every action.
DROP TRIGGER IF EXISTS trg_sync_reel_likes ON public.likes;
DROP TRIGGER IF EXISTS trg_notify_on_like ON public.likes;
DROP TRIGGER IF EXISTS trg_sync_reel_comments ON public.comments;
DROP TRIGGER IF EXISTS trg_notify_on_comment ON public.comments;
DROP TRIGGER IF EXISTS trg_notify_on_follow ON public.follows;
DROP TRIGGER IF EXISTS trg_on_unfollow ON public.follows;
DROP TRIGGER IF EXISTS trg_notify_on_message ON public.messages;

-- Resync counters from the source-of-truth tables so any historical
-- double-counted reels are corrected.
UPDATE public.reels r
SET likes_count = COALESCE(l.c, 0)
FROM (SELECT reel_id, COUNT(*)::int AS c FROM public.likes GROUP BY reel_id) l
WHERE r.id = l.reel_id AND r.likes_count <> l.c;

UPDATE public.reels r SET likes_count = 0
WHERE r.likes_count <> 0 AND NOT EXISTS (SELECT 1 FROM public.likes l WHERE l.reel_id = r.id);

UPDATE public.reels r
SET comments_count = COALESCE(c.c, 0)
FROM (SELECT reel_id, COUNT(*)::int AS c FROM public.comments GROUP BY reel_id) c
WHERE r.id = c.reel_id AND r.comments_count <> c.c;

UPDATE public.reels r SET comments_count = 0
WHERE r.comments_count <> 0 AND NOT EXISTS (SELECT 1 FROM public.comments c WHERE c.reel_id = r.id);

UPDATE public.profiles p
SET followers_count = COALESCE(f.c, 0)
FROM (SELECT following_id, COUNT(*)::int AS c FROM public.follows GROUP BY following_id) f
WHERE p.user_id = f.following_id AND p.followers_count <> f.c;

UPDATE public.profiles p SET followers_count = 0
WHERE p.followers_count <> 0 AND NOT EXISTS (SELECT 1 FROM public.follows f WHERE f.following_id = p.user_id);

UPDATE public.profiles p
SET following_count = COALESCE(f.c, 0)
FROM (SELECT follower_id, COUNT(*)::int AS c FROM public.follows GROUP BY follower_id) f
WHERE p.user_id = f.follower_id AND p.following_count <> f.c;

UPDATE public.profiles p SET following_count = 0
WHERE p.following_count <> 0 AND NOT EXISTS (SELECT 1 FROM public.follows f WHERE f.follower_id = p.user_id);

-- Deduplicate notifications generated by the doubled triggers.
-- Keep the earliest row for each (user_id, actor_id, type, reel_id, content) group.
WITH ranked AS (
  SELECT id,
         ROW_NUMBER() OVER (
           PARTITION BY user_id, actor_id, type, COALESCE(reel_id::text,''), COALESCE(content,'')
           ORDER BY created_at ASC, id ASC
         ) AS rn
  FROM public.notifications
)
DELETE FROM public.notifications n
USING ranked r
WHERE n.id = r.id AND r.rn > 1;
